# coding: utf-8
from __future__ import absolute_import


#/
CFG_K_VAR_D = 'var_d'
CFG_K_VAR_D_K__EXT_CLS_PREFIX = '_EXT_CLS_PREFIX'
CFG_K_VAR_D_K__EXT_CLS_PREFIX_V_DFT = 'aoikfiletypeasso.'
CFG_K_VAR_D_K__SHELLNEW_REMOVE_UNSPECIFIED = '_SHELLNEW_REMOVE_UNSPECIFIED'

#/
CFG_K_EXT_INFO_D = 'ext_d'
CFG_K_EXT_INFO_K_CLS = 'cls'
CFG_K_EXT_INFO_K_CLS_FRIENDLY_TYPE_NAME = 'clsftn'
CFG_K_EXT_INFO_K_EXT_CONTENT_TYPE = 'extct'
CFG_K_EXT_INFO_K_EXT_PERCEIVED_TYPE = 'extpt'
CFG_K_EXT_INFO_K_CMD_INFO_S = 'cmd_s'
CFG_K_EXT_INFO_K_CMD_OPEN = 'open'
CFG_K_EXT_INFO_K_CMD_EDIT = 'edit'
CFG_K_EXT_INFO_K_CMD_DFT = 'cmd_dft'
CFG_K_EXT_INFO_K_SHELLNEW_INFO = 'new'
CFG_K_EXT_INFO_K_ICON = 'icon'
