# coding: utf-8
from __future__ import absolute_import


#/
## 1 and 2 are used by |argparse|.
MAIN_RET_V_KBINT_OK = 0
MAIN_RET_V_VER_SHOW_OK = 0
MAIN_RET_V_EXC_LEAK_ER = 3
MAIN_RET_V_PRODUCING_REGISTRY_DATA_OK = 0
MAIN_RET_V_OPENING_CONFIG_FILE_FAILED = 4
MAIN_RET_V_PARSING_CONFIG_FILE_FAILED = 5
MAIN_RET_V_IMPORTING_TO_REGISTRY_OK = 0
MAIN_RET_V_IMPORTING_TO_REGISTRY_FAILED = 6
MAIN_RET_V_IMPORTING_WIN32COM_FAILED = 7
