# coding: utf-8
"""
File ID: 9n8LYbz
"""

CMD_RET_CODE_V_PRODUCING_REGISTRY_DATA_OK = 0
CMD_RET_CODE_V_OPENING_CONFIG_FILE_FAILED = 1
CMD_RET_CODE_V_PARSING_CONFIG_FILE_FAILED = 2
CMD_RET_CODE_V_IMPORTING_TO_REGISTRY_OK = 0
CMD_RET_CODE_V_IMPORTING_TO_REGISTRY_FAILED = 3
CMD_RET_CODE_V_IMPORTING_WIN32COM_FAILED = 4
