#/ File ID: 8jeVFXR

#/ Caveats
## Modify this config file with your own correct settings
##  before importing data to Windows Registry.

var_d:
  TXT_OPEN_CMD: '"D:\Software\Dev\IDE\Notepad++\0\dst\notepad++.exe" "%1" %*'
  TXT_ICON_PATH: D:\SoftwareData\FileType\TXT\Icon\0.ico
  LOG_ICON_PATH: D:\SoftwareData\FileType\LOG\Icon\0.ico

ext_d:
  txt:
    open: TXT_OPEN_CMD
    icon: TXT_ICON_PATH
    new:
  
  log:
    open: TXT_OPEN_CMD
    icon: LOG_ICON_PATH
